# Generated by Django 6.0.2 on 2026-02-26 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('ECE', 'Electronics & Communication'), ('EEE', 'Electrical & Electronics'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('IT', 'Information Technology'), ('AIDS', 'AI & Data Science'), ('AIML', 'AI & Machine Learning')], db_index=True, max_length=10)),
                ('year', models.IntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year')])),
                ('section', models.CharField(blank=True, max_length=5)),
                ('cgpa', models.DecimalField(db_index=True, decimal_places=2, max_digits=4)),
                ('backlogs', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('placement_status', models.CharField(choices=[('not_placed', 'Not Placed'), ('placed', 'Placed'), ('higher_studies', 'Higher Studies')], db_index=True, default='not_placed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='students.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('10th', '10th Standard'), ('12th', '12th Standard'), ('diploma', 'Diploma'), ('semester', 'Semester')], max_length=20)),
                ('institution', models.CharField(max_length=200)),
                ('board_university', models.CharField(max_length=200)),
                ('year_of_passing', models.IntegerField()),
                ('percentage_cgpa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('semester_number', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='students.studentprofile')),
            ],
            options={
                'ordering': ['exam_type', 'semester_number'],
            },
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['branch', 'cgpa'], name='students_st_branch_20c157_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['placement_status', 'branch'], name='students_st_placeme_a00f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['year', 'branch'], name='students_st_year_42f3e8_idx'),
        ),
    ]
