# Generated by Django 6.0.2 on 2026-03-01 04:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['roll_number']},
        ),
        migrations.RemoveIndex(
            model_name='studentprofile',
            name='students_st_branch_20c157_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentprofile',
            name='students_st_placeme_a00f1d_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentprofile',
            name='students_st_year_42f3e8_idx',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='github_url',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='linkedin_url',
            new_name='linkedin',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['branch', 'placement_status'], name='students_st_branch_492bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['year', 'placement_status'], name='students_st_year_2df428_idx'),
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_photo',
        ),
    ]
