# Generated by Django 6.0.2 on 2026-02-27 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('industry', models.CharField(choices=[('IT', 'Information Technology'), ('CORE', 'Core Engineering'), ('FINANCE', 'Finance & Banking'), ('CONSULTING', 'Consulting'), ('ECOMMERCE', 'E-Commerce'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('MANUFACTURING', 'Manufacturing'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('internship', 'Internship'), ('contract', 'Contract')], default='full_time', max_length=20)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('ctc_min', models.DecimalField(decimal_places=2, help_text='LPA', max_digits=10)),
                ('ctc_max', models.DecimalField(decimal_places=2, help_text='LPA', max_digits=10)),
                ('min_cgpa', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=4)),
                ('max_backlogs', models.IntegerField(default=0)),
                ('eligible_branches', models.JSONField(default=list)),
                ('eligible_years', models.JSONField(default=list)),
                ('application_deadline', models.DateField(db_index=True)),
                ('drive_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('upcoming', 'Upcoming')], db_index=True, default='open', max_length=10)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('vacancy_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'application_deadline'], name='companies_j_status_57607b_idx'), models.Index(fields=['company', 'status'], name='companies_j_company_31d106_idx')],
            },
        ),
    ]
