# Generated by Django 6.0.2 on 2026-03-02 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('students', '0002_alter_studentprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(choices=[('aptitude', 'Aptitude Test'), ('technical', 'Technical Round'), ('hr', 'HR Round'), ('final', 'Final Round'), ('gd', 'Group Discussion')], max_length=20)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], default='offline', max_length=10)),
                ('scheduled_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('meeting_link', models.URLField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='companies.jobpost')),
                ('students', models.ManyToManyField(blank=True, related_name='interviews', to='students.studentprofile')),
            ],
            options={
                'ordering': ['scheduled_date', 'start_time'],
                'indexes': [models.Index(fields=['scheduled_date', 'status'], name='interviews__schedul_d96e1a_idx')],
            },
        ),
    ]
